var checks = new System.Collections.Generic.List<string>();
void Check(bool value, string name) { if (!value) throw new System.Exception(name); checks.Add(name); }
var p = new Pito.Core.PlayerProfile { money = 10, satiety = 20 };
var s = new Pito.Core.GameSession(p);
Check(!s.TryFeed("expensive", 11, 30) && p.money == 10 && p.satiety == 20 && p.operations.Count == 0, "Insufficient funds leave state unchanged");
Check(!s.TryFeed("invalid", -1, 30), "Negative price rejected");
Check(s.TryFeed("apple", 3, 30) && p.money == 7 && p.satiety == 50 && p.operations.Count == 1, "Purchase records exact debit and effect");
s.ChangeNeed(Pito.Core.NeedKind.Satiety, 200);
Check(p.satiety == 100, "Needs capped at 100");
s.ChangeNeed(Pito.Core.NeedKind.Affection, -500);
Check(p.affection == 0, "Needs bounded at zero");
var a = new Pito.Core.GameSession(new Pito.Core.PlayerProfile());
var b = new Pito.Core.GameSession(new Pito.Core.PlayerProfile());
a.Advance(3600, 4, 6, 3);
for (int i=0;i<60;i++) b.Advance(60,4,6,3);
Check(System.Math.Abs(a.Profile.satiety-b.Profile.satiety)<.001 && a.Profile.gameSeconds==b.Profile.gameSeconds, "Batched time equals incremental simulation");
a.Advance(-100,4,6,3);
Check(a.Profile.gameSeconds == 3600, "Negative elapsed time ignored");
string json = UnityEngine.JsonUtility.ToJson(a.Profile);
var restored = UnityEngine.JsonUtility.FromJson<Pito.Core.PlayerProfile>(json);
Check(restored.petTypeId == "pito" && restored.petVariantId == "classic" && restored.satiety == a.Profile.satiety, "Profile type, variant and needs roundtrip");
return checks;
